Refactoring
kstroevsky/websocket-clicker pull request #20
Opened 2022-12-12 17:22 UTC by bogolosv

Refactoring of the NewGamePage component and the components that are included in the NewGamePage component.

2022-12-14 21:43 UTC, kstroevsky requested changes
Very good! I like your passion for refactoring. 
I've added some comments. I hope, it will be useful for you, and I also wait for your questions and fixes, of course.

2022-12-14 21:43 UTC, kstroevsky commented on client/src/components/GameDetails/AddForm.tsx
>                  onClick={() => clickHandler()}
```suggestion
                onClick={clickHandler}
```

2022-12-14 21:43 UTC, kstroevsky commented on client/src/pages/GamePage.tsx
>                      onClick={() => copy()}
Also, it will be good to rename it with handleClipboardCopy, for example.
```suggestion
                    onClick={copy}
```

2022-12-14 21:43 UTC, kstroevsky commented on client/src/pages/NewGamePage.tsx
> +                            disabledBtn={nameUser === '' || joinUrl === ''}
What do you think? Or do we necessarily need to check an empty string?
```suggestion
                            disabledBtn={!(nameUser && joinUr)}
```

2022-12-14 21:43 UTC, kstroevsky commented on client/src/components/GameDetails/CreateGameForm.tsx
> +                placeholder="Game Duration"
I think, **hardcoded strings** in `props` also need to move in the `constants` file.

2022-12-14 21:43 UTC, kstroevsky commented on client/src/components/GameDetails/CreateGameForm.tsx
>          onClick={() => clickHandler()}
```suggestion
        onClick={clickHandler}
```

2022-12-15 22:07 UTC, kstroevsky requested changes
Good. The main part of my comments is about my war with your lines' wrapping style ;)) 

Also, am I understanding right you already started implementing PWA in the current PR?

After, I think, I try to teach you to configure lint and prettier.

2022-12-16 09:25 UTC, bogolosv commented on client/public/service-worker.js
> +});
Yes, it is. During the finding of the solution for the PWA application, I was inspired by the [topic](https://medium.com/@addyosmani/progressive-web-apps-with-react-js-part-3-offline-support-and-network-resilience-c84db889162c).
Yes, I did. The checking of the compatibility with `service workers` is in the `public/index.html`

2022-12-16 09:27 UTC, bogolosv commented on client/public/index.html
> +    </script>
This is checking the compatibility with `service workers` and registration of the file `service-worker.js`

2022-12-16 09:52 UTC, kstroevsky commented on client/public/index.html
> +    </script>
> Это проверка совместимости `service workers`и регистрация файла`service-worker.js`
What is the way if the browser or OS is not compatible with service workers? Will the application crash? Or what?

2022-12-16 10:03 UTC, kstroevsky commented on client/public/index.html
> +    </script>
> if the browser supports it, then we wait for the page to load, and after that, we register our Service Worker by loading the `service-worker.js` file. Application is not going to be created if the browser doesn't support the service worker

Can you make the application will work even browser doesn't support service workers? Like in a previous way without PWA. Without service workers, of course.

So, like try/catch:
If the browser supports service workers => we create a PWA application. 
Else => we create a simple react application.

2022-12-19 12:24 UTC, kstroevsky approved these changes
💯

2022-12-19 12:25 UTC, merged